[package]
name = "winrt-notification"
version = "0.1.2"
authors = ["allenbenz"]
keywords = ["notification", "windows", "toast", "notify"]
readme = "README.md"
description = "An incomplete wrapper over the WinRT toast api"
repository = "https://github.com/allenbenz/winrt-notification"
license = "MIT"
exclude = [
    ".vscode/*"
]

[package.metadata.docs.rs]
default-target = "x86_64-pc-windows-msvc"

[dependencies.winrt]
version = "0.3.0"
features = ["windows-data", "windows-ui"]

[dependencies]
xml-rs = "0.6.1"
